- name: Install Docker
  hosts: junnon_servers
  become: yes

  tasks:
    - name: Install Docker when OS is RedHat/CentOS/Amazon
      package:
        name: docker
        state: latest
      when: ansible_distribution in ['CentOS', 'RedHat', 'Amazon']

    - name: Install Docker when OS is Ubuntu
      package:
        name: docker.io
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Start Docker on CentOS and Amazon
      systemd_service:
        name: docker
        state: started
      when: ansible_distribution in ['CentOS', 'Amazon']

    - name: Start Docker on RHEL
      systemd_service:
        name: docker.service
        state: started
      when: ansible_distribution == "RedHat"

       

