- 
  name: Install Nginx
  hosts: junnon_servers
  become: yes

  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: latest  
    
    - name: Start Nginx
      systemd_service: 
         name: nginx
         state: started      
         
    - name: Enable Nginx
      systemd_service:
           name: nginx
           state: reloaded      
